(function(){
'use strict';
const $=id=>document.getElementById(id), n=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
let data=null, transposed=false, scroll={x:0,y:0}, cell=null;
async function request(body){const r=await fetch('php/ajax/vz2_history.php',{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:body?{'Content-Type':'application/json','X-CSRF-Token':window.VZ2.csrf}:{},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Historii nelze načíst.');return j;}
function playable(p){return [p.clip,p.source].some(r=>r?.files?.some(f=>f.url));}
function clock(ms){let s=Math.floor(ms/1000),h=Math.floor(s/3600);s%=3600;return (h?h+':':'')+String(Math.floor(s/60)).padStart(h?2:1,'0')+':'+String(s%60).padStart(2,'0');}
function title(p){return p.clip?.title||p.clip_title||clock(p.start_ms||0);}
function option(value,text){const o=n('option',text);o.value=value;return o;}
function refreshFilter(){const select=$('history-song-filter'),v=select.value;select.replaceChildren(option('','Všechny skladby'));data.songs.forEach(s=>select.append(option(s.id,s.title)));select.value=v;}
function render(){refreshFilter();const selected=Number($('history-song-filter').value)||null, onlyAudio=$('history-audio-filter').checked;
 const songs=data.songs.filter(s=>!selected||Number(s.id)===selected), rehearsals=data.rehearsals, rows=transposed?songs:rehearsals, cols=transposed?rehearsals:songs;
 const table=n('table');table.className='history-table';const head=n('thead'),hr=n('tr');hr.append(n('th',transposed?'Skladba':'Zkouška'));cols.forEach(c=>{const th=n('th',c.title);th.title=c.title;hr.append(th);});head.append(hr);table.append(head);const body=n('tbody');
 rows.forEach(row=>{const tr=n('tr'),rh=n('th',row.title);rh.title=row.title;tr.append(rh);cols.forEach(col=>{const song=transposed?row:col,rehearsal=transposed?col:row,td=n('td');let plays=data.plays.filter(p=>p.song_collection_id==song.id&&p.rehearsal_collection_id==rehearsal.id);plays.forEach(p=>{const ok=playable(p);if(onlyAudio&&!ok)return;const b=n('button',title(p),'history-play'+(ok?'':' no-audio'));b.type='button';b.title=(p.clip?'Výstřižek: ':'Zahrání od ')+title(p)+(ok?'':' — audio není dostupné ('+(p.clip?.audio_state||p.source?.audio_state||'bez zdroje')+')');b.setAttribute('aria-label',b.title);b.onclick=()=>detail(p);td.append(b);});
 if(data.can_edit){const add=n('button','+','history-add');add.type='button';add.title='Zařadit existující úsek nebo výstřižek';add.onclick=()=>openAdd(song,rehearsal);td.append(add);}tr.append(td);});body.append(tr);});table.append(body);$('history-matrix').replaceChildren(table);$('history-matrix').scrollTo(scroll.x,scroll.y);}
function audioButton(recording,label,start=0){const f=recording?.files?.find(x=>x.url);if(!f)return null;const a=n('audio');a.controls=true;a.preload='none';a.src=f.url;a.addEventListener('loadedmetadata',()=>{a.currentTime=start/1000;},{once:true});const box=n('div');box.append(n('strong',label),a);return box;}
function details(label,contents){const d=n('details'),s=n('summary',label);d.append(s,...contents);return d;}
function detail(p){const body=$('history-detail').querySelector('.history-detail-body');body.replaceChildren(n('p',p.song_title+' × '+p.rehearsal_title),n('small','Zahrání #'+p.id));const quick=n('div','', 'history-listen');const clipAudio=audioButton(p.clip,'Výstřižek');const sourceAudio=audioButton(p.source,'Původní nahrávka',p.start_ms);if(clipAudio)quick.append(clipAudio);if(sourceAudio)quick.append(sourceAudio);body.append(quick);
 if(p.clip)body.append(details('Výstřižek',[n('p',p.clip.title),n('p',p.clip.summary||'Bez popisu.'),n('small','Audio: '+p.clip.audio_state)]));
 if(p.source)body.append(details('Původní nahrávka',[n('p',p.source.title),n('p',(p.start_ms===null?'bez času':Vz2Timestamps.format(p.start_ms)+' – '+Vz2Timestamps.format(p.end_ms))),n('small','Audio: '+p.source.audio_state)]));
 if(p.source)body.append(details('Poznámky ('+p.notes.length+')',p.notes.length?p.notes.map(x=>n('p',Vz2Timestamps.format(x.time_ms)+' · '+x.body)):[n('p','Žádné poznámky v úseku.')]));
 if(p.can_edit){const controls=[];const clips=data.unassigned_clips.filter(c=>c.collection_id==p.song_collection_id);const sel=n('select');sel.append(option('','Odpojit výstřižek'));if(p.clip_recording_id)sel.append(option(p.clip_recording_id,p.clip_title));clips.forEach(c=>sel.append(option(c.id,c.title)));sel.value=p.clip_recording_id||'';const save=n('button','Uložit výstřižek');save.onclick=async()=>{data=await request({action:'update',id:p.id,revision:p.revision,song_collection_id:p.song_collection_id,rehearsal_collection_id:p.rehearsal_collection_id,source_recording_id:p.source_recording_id,start_timestamp_id:p.start_timestamp_id,end_timestamp_id:p.end_timestamp_id,clip_recording_id:sel.value?Number(sel.value):null});$('history-detail').close();render();};const del=n('button','Odebrat zahrání');del.className='danger';del.onclick=async()=>{if(!confirm('Odebrat pouze historické zahrání? Audio ani značky se nesmažou.'))return;data=await request({action:'delete',id:p.id,revision:p.revision});$('history-detail').close();render();};controls.push(sel,save,del);body.append(details('Úpravy',controls));}
 $('history-detail').showModal();}
function openAdd(song,rehearsal){cell={song,rehearsal};const box=$('history-add').querySelector('.history-candidates');box.replaceChildren();data.unassigned_intervals.filter(i=>i.rehearsal_collection_id==rehearsal.id).forEach(i=>{const l=n('label');const r=n('input');r.type='radio';r.name='candidate';r.value='i:'+i.recording_id+':'+i.start_timestamp_id+':'+i.end_timestamp_id;l.append(r,document.createTextNode(' Úsek '+i.recording_title+' · '+clock(i.start_ms)+'–'+clock(i.end_ms)));box.append(l);});data.unassigned_clips.filter(c=>c.collection_id==song.id).forEach(c=>{const l=n('label');const r=n('input');r.type='radio';r.name='candidate';r.value='c:'+c.id;l.append(r,document.createTextNode(' Výstřižek '+c.title+' · '+c.audio_state));box.append(l);});if(!box.children.length)box.append(n('p','Pro tuto buňku není žádný dokončený nezařazený úsek ani volný výstřižek.'));$('history-add').querySelector('.history-context').textContent=song.title+' × '+rehearsal.title;$('history-add').showModal();}
$('history-add').querySelector('form').onsubmit=async e=>{e.preventDefault();const chosen=new FormData(e.currentTarget).get('candidate');if(!chosen){e.currentTarget.querySelector('.error').textContent='Vyberte podklad.';return;}const parts=chosen.split(':'),body={action:'create',song_collection_id:Number(cell.song.id),rehearsal_collection_id:Number(cell.rehearsal.id),source_recording_id:null,start_timestamp_id:null,end_timestamp_id:null,clip_recording_id:null};if(parts[0]==='c')body.clip_recording_id=Number(parts[1]);else{body.source_recording_id=Number(parts[1]);body.start_timestamp_id=Number(parts[2]);body.end_timestamp_id=Number(parts[3]);}try{data=await request(body);$('history-add').close();render();}catch(err){e.currentTarget.querySelector('.error').textContent=err.message;}};
document.querySelectorAll('[data-history-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('show-history').onclick=async()=>{scroll={x:0,y:0};$('history-workspace').hidden=false;$('app-shell').hidden=true;try{data=await request();render();$('history-status').textContent='';}catch(e){$('history-status').textContent=e.message;}};
$('history-close').onclick=()=>{$('history-workspace').hidden=true;$('app-shell').hidden=false;};$('history-orientation').onclick=e=>{transposed=!transposed;e.currentTarget.setAttribute('aria-pressed',String(transposed));render();};$('history-song-filter').onchange=render;$('history-audio-filter').onchange=render;$('history-matrix').onscroll=e=>{scroll={x:e.currentTarget.scrollLeft,y:e.currentTarget.scrollTop};};
})();
