'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
module.exports = async function ({ base, clients, good, request, db, check, temp, upload, wav }) {
    const collection = await good('admin',{action:'collection_create',kind:'song',title:'Etapa 4 — společné texty'});
    const second = await good('admin',{action:'collection_create',kind:'rehearsal',title:'Jiná zkouška'});
    collection.title = 'Etapa 4 — společné texty'; second.title = 'Jiná zkouška';
    const endpoint = 'php/ajax/vz2_content.php';
    const query = {action:'document',collection_id:collection.id,kind:'lyrics_chords'};
    const get = (who, fields) => request(clients[who],endpoint+'?'+new URLSearchParams(fields));
    const post = (who, fields) => request(clients[who],endpoint,fields);
    const executablePath = [process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,chromium.executablePath(),'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(p=>p && fs.existsSync(p));
    const browser = await chromium.launch({headless:true,executablePath});
    const errors=[];
    async function openPanelEditor(page, id) {
        const toggle = page.locator('[data-desktop-panel="' + id + '"]');
        if (await toggle.getAttribute('aria-pressed') === 'false') await toggle.click();
        await page.locator('#' + id + '-content > button').first().click();
    }
    async function pageFor(who) {
        const context=await browser.newContext({viewport:{width:1440,height:1000}});
        const [name,value]=clients[who].cookie.split('='); await context.addCookies([{name,value,url:base}]);
        const page=await context.newPage(); page.on('pageerror',e=>errors.push(e.message)); page.on('dialog',d=>d.accept());
        await page.route('https://cdn.jsdelivr.net/**',r=>r.abort());
        await page.goto(base+'index.php?v=2&collection_id='+collection.id); return page;
    }
    try {
        const page=await pageFor('admin'), dlg=page.locator('.vz2-content-dialog');
        await openPanelEditor(page, 'lyrics');
        await dlg.getByText('Dokument se vytvoří při prvním uložení.',{exact:true}).waitFor();
        const body=dlg.locator('[name=document_body]');
        const original='  C         G\nText písně <img src=x onerror=alert(1)>\n';
        await body.fill(original); await dlg.getByRole('button',{name:'Uložit novou verzi',exact:true}).click();
        await dlg.getByText('Nová verze uložena.',{exact:true}).waitFor();
        assert.equal(await body.inputValue(),original); assert.equal(await dlg.locator('img').count(),0);
        await body.fill('Moje rozepsaná verze');
        let stored=(await get('admin',query)).json();
        assert.equal((await post('bob',{action:'document_save',collection_id:collection.id,kind:'lyrics_chords',document_id:stored.document.id,current_revision:stored.document.current_revision,title:'Text a akordy',body:'Cizí souběžná úprava'})).status,200);
        await dlg.getByRole('button',{name:'Uložit novou verzi',exact:true}).click();
        await dlg.getByRole('button',{name:'Načíst aktuální verzi k porovnání',exact:true}).waitFor();
        assert.equal(await body.inputValue(),'Moje rozepsaná verze');
        await dlg.getByRole('button',{name:'Načíst aktuální verzi k porovnání',exact:true}).click();
        await dlg.locator('pre').filter({hasText:'Cizí souběžná úprava'}).waitFor();
        await dlg.getByRole('button',{name:'Použít aktuální revizi pro můj text',exact:true}).click();
        await dlg.getByRole('button',{name:'Uložit novou verzi',exact:true}).click();
        await dlg.getByText('Nová verze uložena.',{exact:true}).waitFor();
        assert.equal((await get('admin',query)).json().document.current_revision,3);
        check(true,'browser: document conflict preserves draft, shows current text and requires explicit revision acceptance');
        await dlg.getByRole('button',{name:'Historie verzí',exact:true}).click();
        await dlg.getByRole('button',{name:/^Verze 1 ·/}).click();
        await dlg.getByRole('button',{name:'Obnovit jako novou verzi',exact:true}).click();
        await dlg.getByText('Obnoveno jako nová verze.',{exact:true}).waitFor();
        assert.equal(await body.inputValue(),original); assert.equal((await get('admin',query)).json().document.current_revision,4);
        await body.fill('Koncept po obnovení katalogu'); await page.evaluate(()=>window.dispatchEvent(new Event('online')));
        await page.locator('#collection-title').getByText(collection.title,{exact:true}).waitFor();
        assert.equal(await body.inputValue(),'Koncept po obnovení katalogu');
        await dlg.getByRole('button',{name:'Zavřít',exact:true}).click();
        await openPanelEditor(page, 'lyrics');
        await dlg.locator('[name=document_body]:enabled').waitFor();
        assert.equal(await body.inputValue(),original);
        check(true,'browser: history restore creates revision 4, draft survives catalogue refresh and discard leaves saved content unchanged');
        await page.setViewportSize({width:390,height:844}); await page.screenshot({path:path.join(temp,'stage4-document-mobile.png')});
        assert(await dlg.evaluate(d=>d.scrollWidth<=d.clientWidth+1),'document dialog must fit mobile');
        await page.setViewportSize({width:1440,height:1000}); await page.screenshot({path:path.join(temp,'stage4-document-desktop.png')});
        await dlg.getByRole('button',{name:'Zavřít',exact:true}).click();
        await openPanelEditor(page, 'tablature');
        await body.fill('e|---0---2---|\nB|---1---3---|\n'); await dlg.getByRole('button',{name:'Uložit novou verzi',exact:true}).click();
        await dlg.getByText('Nová verze uložena.',{exact:true}).waitFor(); await dlg.getByRole('button',{name:'Zavřít',exact:true}).click();
        check((await get('admin',query)).json().version.body===original,'browser: separate tablature does not replace lyrics/chords');
        await openPanelEditor(page, 'discussion');
        await dlg.locator('[name=post_body]').fill('Adminův příspěvek'); await dlg.getByRole('button',{name:'Odeslat',exact:true}).click();
        await dlg.locator('article').getByText('Adminův příspěvek',{exact:true}).waitFor();
        await dlg.getByRole('button',{name:'Zavřít',exact:true}).click();
        const bob=await pageFor('bob'), member=bob.locator('.vz2-content-dialog');
        await openPanelEditor(bob, 'discussion');
        await member.locator('article').getByText('Adminův příspěvek',{exact:true}).waitFor();
        assert.equal(await member.locator('article button').count(),0);
        await member.locator('[name=post_body]').fill('Bobův příspěvek <script>alert(1)</script>'); await member.getByRole('button',{name:'Odeslat',exact:true}).click();
        const own=member.locator('article').filter({hasText:'Bobův příspěvek'}); await own.waitFor(); assert.equal(await member.locator('script').count(),0);
        await own.getByRole('button',{name:'Upravit',exact:true}).click(); await member.locator('[name=post_body]').fill('Bobův koncept');
        const thread=(await get('admin',{action:'discussion',collection_id:collection.id})).json(); const p=thread.posts.find(p=>p.created_by===3);
        assert.equal((await post('admin',{action:'post_update',thread_id:thread.thread.id,post_id:p.id,revision:p.revision,body:'Admin upravil Bobův příspěvek'})).status,200);
        await member.getByRole('button',{name:'Uložit úpravu',exact:true}).click();
        await member.getByRole('button',{name:'Načíst aktuální příspěvek',exact:true}).waitFor(); assert.equal(await member.locator('[name=post_body]').inputValue(),'Bobův koncept');
        await member.getByRole('button',{name:'Načíst aktuální příspěvek',exact:true}).click(); await member.locator('pre').getByText(/Admin upravil/).waitFor();
        await member.getByRole('button',{name:'Použít aktuální revizi pro můj text',exact:true}).click(); await member.getByRole('button',{name:'Uložit úpravu',exact:true}).click();
        await member.locator('article').getByText('Bobův koncept',{exact:true}).waitFor();
        check(true,'browser: foreign post has no edit buttons; own post conflict retains draft and explicit resolution works');
        await member.locator('article').filter({hasText:'Bobův koncept'}).getByRole('button',{name:'Smazat',exact:true}).click();
        await member.locator('article').getByText('Bobův koncept',{exact:true}).waitFor({state:'detached'});
        await member.getByRole('button',{name:'Zavřít',exact:true}).click();
        const ideas = bob.locator('#ideas-workspace');
        await bob.getByRole('button',{name:'Nápady',exact:true}).click(); await ideas.locator('[name=post_body]').fill('Společný nápad');
        await ideas.getByRole('button',{name:'Odeslat',exact:true}).click(); await ideas.locator('article').getByText('Společný nápad',{exact:true}).waitFor();
        await ideas.getByRole('button',{name:'Zpět k panelům',exact:true}).click();
        const guest=await pageFor('guest'), readOnly=guest.locator('.vz2-content-dialog');
        await openPanelEditor(guest, 'lyrics');
        await readOnly.locator('[name=document_body]:enabled').waitFor();
        assert.equal(await readOnly.locator('[name=document_body]').inputValue(),original);
        assert.equal(await readOnly.locator('[name=document_body]').evaluate(n=>n.readOnly),true);
        assert.equal(await readOnly.getByRole('button',{name:'Uložit novou verzi',exact:true}).isVisible(),false);
        await readOnly.getByRole('button',{name:'Historie verzí',exact:true}).click(); await readOnly.getByRole('button',{name:/^Verze 1 ·/}).click();
        assert.equal(await readOnly.getByRole('button',{name:'Obnovit jako novou verzi',exact:true}).isVisible(),false);
        await readOnly.getByRole('button',{name:'Zavřít',exact:true}).click(); await guest.getByRole('button',{name:'Nápady',exact:true}).click();
        await guest.locator('#ideas-workspace article').getByText('Společný nápad',{exact:true}).waitFor(); assert.equal(await guest.locator('#ideas-workspace form').isVisible(),false);
        check(true,'browser: own post deletion works; global ideas shared with guest; guest sees documents/history without write controls');
        await openPanelEditor(page, 'discussion');
        await dlg.locator('article').getByText('Adminův příspěvek',{exact:true}).waitFor();
        assert.equal(await dlg.getByText('Společný nápad',{exact:true}).count(),0);
        await page.setViewportSize({width:390,height:844}); await page.screenshot({path:path.join(temp,'stage4-discussion-mobile.png')});
        assert(await dlg.evaluate(d=>d.scrollWidth<=d.clientWidth+1),'discussion dialog must fit mobile');
        await page.setViewportSize({width:1440,height:1000}); await page.screenshot({path:path.join(temp,'stage4-discussion-desktop.png')});
        await dlg.getByRole('button',{name:'Zavřít',exact:true}).click();
        await page.getByRole('button',{name:'Zkoušky',exact:true}).click(); await page.getByRole('button',{name:second.title,exact:true}).click(); await openPanelEditor(page, 'discussion');
        await dlg.getByText('Zatím žádné příspěvky.',{exact:true}).waitFor(); await dlg.getByRole('button',{name:'Zavřít',exact:true}).click();
        const mix=await upload('admin',collection.id,'Mixér s diskusí','multitrack',['left.wav','right.wav'],[wav(1),wav(1)]); assert.equal(mix.status,201,mix.text);
        await page.goto(base+'index.php?v=2&view=mixer&recording_id='+mix.json().id);
        await page.waitForFunction(()=>window.MultitrackApp?.getState()?.phase==='ready');
        await page.getByRole('button',{name:'Diskuse ke skladbě / zkoušce',exact:true}).click();
        await dlg.locator('article').getByText('Adminův příspěvek',{exact:true}).waitFor();
        assert.deepEqual(errors,[]);
        check(true,'browser: collection scopes stay separate, Mixer opens its parent discussion, mobile layouts fit and no JS errors occur');
    } finally { await browser.close(); }
    for(const c of [collection,second]) {
        const row=db('SELECT * FROM vz2_collections WHERE id=?',[c.id])[0];
        await good('admin',{action:'delete_collection',id:c.id,revision:row.revision,confirm:row.title,request_key:require('node:crypto').randomBytes(16).toString('hex')});
    }
};
