'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path');
const { chromium } = require('playwright');
module.exports = async ({ base, clients, good, upload, wav, request, check, temp }) => {
    const collection = await good('admin', { action: 'collection_create', kind: 'song', title: 'Looper a Mixér' });
    const tone = wav(20);
    for (let i = 0; i < (tone.length - 44) / 2; i++) tone.writeInt16LE(Math.round(Math.sin(i / 8000 * 220 * Math.PI * 2) * (0.15 + 0.5 * Math.abs(Math.sin(i / 8000 * 1.7))) * 32767), 44 + i * 2);
    const single = (await upload('admin', collection.id, 'Kytara', 'single', ['guitar.wav'], [tone])).json();
    const mix = (await upload('admin', collection.id, 'Celá kapela', 'multitrack', ['bass.wav', 'drums.wav'], [wav(20), wav(20)])).json();
    const executablePath = [process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH, chromium.executablePath(), 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(p => p && fs.existsSync(p));
    const browser = await chromium.launch({ headless: true, executablePath, args: ['--autoplay-policy=no-user-gesture-required'] });
    try {
        const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, permissions: ['clipboard-read', 'clipboard-write'] });
        const [name, value] = clients.admin.cookie.split('='); await context.addCookies([{ name, value, url: base }]);
        await context.addInitScript(() => {
            window.audioStarts = []; window.revokedAudio = []; window.audioStops = 0;
            const start = AudioBufferSourceNode.prototype.start;
            AudioBufferSourceNode.prototype.start = function (when, offset, ...args) { window.audioStarts.push({ when, offset }); return start.call(this, when, offset, ...args); };
            const stop = AudioBufferSourceNode.prototype.stop;
            AudioBufferSourceNode.prototype.stop = function (...args) { window.audioStops++; return stop.apply(this, args); };
            const revoke = URL.revokeObjectURL; URL.revokeObjectURL = function (url) { window.revokedAudio.push(url); return revoke.call(this, url); };
        });
        const page = await context.newPage(), errors = []; page.on('pageerror', e => errors.push(e.message));
        await page.route('https://cdn.jsdelivr.net/**', r => r.abort());
        let allow = true, confirmations = 0;
        page.on('dialog', d => { confirmations++; return allow ? d.accept() : d.dismiss(); });
        await page.goto(base + 'index.php?v=2&collection_id=' + collection.id);
        const openLooper = () => page.locator('#recording-' + single.id).getByRole('button', { name: 'Otevřít', exact: true }).click();
        const openMixer = () => page.locator('#recording-' + mix.id).getByRole('button', { name: 'Otevřít Mixér', exact: true }).click();
        const state = () => page.evaluate(() => window.Vz2Player.getState());
        const ready = mode => page.waitForFunction(mode => { const s = window.Vz2Player.getState(); return s?.mode === mode && s.phase === 'ready' && !s.loading; }, mode);
        await openLooper(); await ready('looper');
        assert.equal(await page.locator('#mixer-panel').isVisible(), false);
        assert.equal(await page.locator('.recording-toggle[aria-expanded=true]').count(), 0);
        assert.equal(await page.locator('#looper-wave').evaluate(n => n.width > 0), true);
        assert.equal(await page.locator('#looper-restart .ti-player-track-prev').count(), 1);
        assert.equal(await page.locator('#looper-loop .ti-repeat').count(), 1);
        await page.locator('#looper-mute').click();
        assert.equal(await page.locator('#looper-audio').evaluate(a => a.muted), true);
        await page.locator('#looper-mute').click();
        await page.locator('#looper-zoom-in').click();
        assert.equal(await page.locator('#looper-zoom').inputValue(), '2');
        assert(await page.locator('#looper-wave').evaluate(n => { const p = n.getContext('2d').getImageData(0, 0, n.width, n.height).data; let filled = 0; for (let i = 3; i < p.length; i += 4) if (p[i]) filled++; return filled > n.width * 2; }), 'Waveform must reflect non-silent audio');
        await page.locator('#looper-seek').evaluate(n => { n.value = 3; n.dispatchEvent(new Event('input', { bubbles: true })); });
        await page.locator('#player-collapse').click();
        assert.equal((await state()).collapsed, true); assert.equal((await state()).position, 3);
        await page.locator('#looper-options > summary').click();
        assert.equal(await page.locator('#looper-menu').isVisible(), true);
        await page.locator('#looper-fullscreen').click();
        assert.equal((await state()).fullscreen, true); assert.equal((await state()).collapsed, false);
        assert.deepEqual(await page.locator('#player-shell').evaluate(n => { const r = n.getBoundingClientRect(); return [r.x, r.y, r.width, r.height]; }), [0, 0, 1440, 900]);
        await page.locator('#looper-zoom').evaluate(n => { n.value = 4; n.dispatchEvent(new Event('input', { bubbles: true })); });
        await page.screenshot({ path: path.join(temp, 'ui-stage3-looper-desktop.png') });
        await page.keyboard.press('Escape');
        assert.equal((await state()).collapsed, true); assert.equal((await state()).position, 3);
        await page.locator('#player-collapse').click();
        await page.locator('#looper-play').click(); await page.waitForFunction(() => window.Vz2Player.getState().playing);
        allow = false; await openMixer();
        assert.equal((await state()).mode, 'looper'); assert.equal((await state()).playing, true);
        const url = await page.locator('#looper-audio').getAttribute('src');
        await page.evaluate(() => { window.previousAudio = document.getElementById('looper-audio'); });
        allow = true; await openMixer(); await ready('mixer');
        assert.equal(await page.locator('#looper-audio').count(), 0);
        assert.equal(await page.evaluate(() => window.previousAudio.paused && !window.previousAudio.hasAttribute('src')), true);
        assert.equal(await page.evaluate(url => window.revokedAudio.includes(url), url), true);
        assert.equal(confirmations, 2);
        check(true, 'player: Looper fullscreen restores collapse/time; cancelled switch keeps playback; accepted switch releases HTML audio and blob URL');
        await page.locator('#player-play').click(); await page.waitForFunction(() => window.MultitrackApp.getState().playing);
        const starts = await page.evaluate(() => window.audioStarts.slice(-2));
        assert.equal(starts.length, 2); assert.equal(starts[0].when, starts[1].when); assert.equal(starts[0].offset, starts[1].offset);
        await page.locator('#player-collapse').click(); assert.equal((await state()).playing, true);
        await page.locator('#player-fullscreen').click();
        assert.equal((await state()).playing, true);
        await page.locator('.mt-mute').first().click(); assert.equal((await page.evaluate(() => window.MultitrackApp.getState())).tracks[0].muted, true);
        await page.locator('.mt-solo').last().click(); assert.equal((await page.evaluate(() => window.MultitrackApp.getState())).tracks[1].solo, true);
        await page.screenshot({ path: path.join(temp, 'ui-stage3-mixer-desktop.png') });
        await page.keyboard.press('Escape'); assert.equal((await state()).collapsed, true);
        const before = confirmations, stops = await page.evaluate(() => window.audioStops);
        allow = false; await openLooper(); assert.equal((await state()).mode, 'mixer'); assert.equal((await state()).playing, true);
        allow = true; await openLooper(); await ready('looper');
        assert.equal(confirmations, before + 2);
        assert((await page.evaluate(() => window.audioStops)) > stops);
        assert.equal(await page.evaluate(() => window.MultitrackApp.getState()), null);
        const idle = confirmations; await openMixer(); await ready('mixer'); await openLooper(); await ready('looper');
        assert.equal(confirmations, idle, 'Idle tools switch directly');
        check(true, 'player: shared Mixer transport preserves identical track start times, Mute/Solo and playback through collapse/fullscreen; idle switch is direct');
        const notes = await request(clients.admin, 'php/ajax/vz2_timestamps.php?recording_id=' + single.id);
        assert.equal((await request(clients.admin, 'php/ajax/vz2_timestamps.php', { action: 'create', recording_id: single.id, timestamps_revision: notes.json().timestamps_revision, kind: 'passage', time_ms: 1000, body: 'Pasáž pro Looper' })).status, 201);
        await page.locator('#looper-timestamps').getByRole('button', { name: 'Obnovit zápisy', exact: true }).click();
        await page.locator('#looper-timestamps').getByRole('button', { name: 'Smyčka', exact: true }).click();
        await page.waitForFunction(() => window.Vz2Player.getState().playing);
        await page.locator('#looper-audio').evaluate(a => a.currentTime = 19.99);
        await page.waitForFunction(() => document.getElementById('looper-audio').currentTime < 2);
        await page.locator('#looper-timestamps').getByRole('button', { name: 'Vypnout smyčku', exact: true }).click();
        await page.locator('#looper-play').click();
        await page.locator('#looper-options > summary').click(); await page.locator('#looper-copy-link').click();
        const copied = await page.evaluate(() => navigator.clipboard.readText());
        await page.goto(copied); await ready('looper');
        assert(Math.abs((await state()).position - Number(new URL(copied).searchParams.get('time_ms')) / 1000) < .1);
        for (const width of [360, 390, 767, 768, 1024, 1199, 1200, 1280, 1440, 1920]) {
            await page.setViewportSize({ width, height: 700 });
            await page.waitForFunction(expected => document.body.dataset.layout === expected, width < 768 ? 'mobile' : width < 1200 ? 'tablet' : 'desktop');
            assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight), 'Active Looper fits ' + width);
        }
        await page.setViewportSize({ width: 390, height: 844 });
        await page.locator('#looper-options > summary').click(); await page.locator('#looper-fullscreen').click();
        await page.screenshot({ path: path.join(temp, 'ui-stage3-looper-mobile.png') });
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
        await page.locator('#looper-options > summary').click(); await page.locator('#looper-close').click();
        assert.equal(await state(), null); assert.equal(await page.locator('#player-body').isVisible(), false);
        check(true, 'player: shared passage loop, copied Looper deep-link time, mobile CSS fullscreen and closing to empty bar');
        // Delay the single-audio fetch, then switch; the late response must never resurrect it.
        let reached, release; const waiting = new Promise(r => reached = r), held = new Promise(r => release = r);
        const catalog = (await request(clients.admin, 'php/ajax/vz2.php?action=catalog')).json();
        const fileId = catalog.recordings.find(r => Number(r.id) === Number(single.id)).files[0].id;
        const matcher = url => url.pathname.endsWith('vz2_files.php') && url.searchParams.get('type') === 'audio' && url.searchParams.get('id') === String(fileId);
        await page.route(matcher, async route => { reached(); await held; await route.abort(); });
        await openLooper(); await waiting;
        assert.equal((await state()).loading, true);
        await openMixer(); release(); await ready('mixer');
        assert.equal(await page.locator('#looper-audio').count(), 0);
        await page.unroute(matcher);
        await page.locator('#player-close').click();
        assert.equal(await page.evaluate(() => window.MultitrackApp.getState()), null);
        assert.deepEqual(errors, []);
        check(true, 'player: cancelling Looper fetch during switch cannot restore old audio; closing Mixer releases its active set; no JS errors');
    } finally { await browser.close(); }
};
