'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path');
const { chromium } = require('playwright');
module.exports = async ({ base, clients, good, request, check, temp, upload, wav }) => {
    const collection = await good('admin', { action: 'collection_create', kind: 'song', title: 'Nápady a návrat k panelům' });
    const single = (await upload('admin', collection.id, 'Pracovní audio', 'single', ['take.wav'], [wav(30)])).json();
    const endpoint = 'php/ajax/vz2_content.php';
    const thread = (await request(clients.admin, endpoint + '?action=discussion&scope=ideas')).json().thread;
    const original = 'Dlouhý nápad ' + 'slovo'.repeat(100) + '\n' + 'Další řádek\n'.repeat(45);
    const post = await request(clients.admin, endpoint, { action: 'post_create', thread_id: thread.id, body: original });
    assert.equal(post.status, 200, post.text);
    const executablePath = [process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH, chromium.executablePath(), 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(p => p && fs.existsSync(p));
    const browser = await chromium.launch({ headless: true, executablePath, args: ['--autoplay-policy=no-user-gesture-required'] });
    try {
        const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
        const [name, value] = clients.admin.cookie.split('='); await context.addCookies([{ name, value, url: base }]);
        const page = await context.newPage(), errors = [];
        page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => d.accept());
        await page.route('https://cdn.jsdelivr.net/**', r => r.abort());
        await page.goto(base + 'index.php?v=2&collection_id=' + collection.id);
        await page.locator('#recording-' + single.id).getByRole('button', { name: 'Otevřít', exact: true }).click();
        await page.waitForFunction(() => window.Vz2Player.getState()?.phase === 'ready');
        await page.locator('#player-play').click();
        const prefs = () => page.evaluate(() => Object.fromEntries(Object.entries(localStorage).filter(([k]) => k.includes('layout:'))));
        const before = await prefs();
        await page.locator('#show-ideas').click();
        const ideas = page.locator('#ideas-workspace');
        await ideas.locator('article').filter({ hasText: 'Dlouhý nápad' }).waitFor();
        assert.equal(await page.locator('dialog[open]').count(), 0);
        assert.equal(await page.locator('#content-area').isVisible(), false);
        assert.equal(await page.evaluate(() => window.Vz2Player.getState().collapsed), true);
        assert.equal(await page.evaluate(() => window.Vz2Player.getState().playing), true);
        const draft = ideas.locator('[name=post_body]'); await draft.fill('Koncept přežije návrat i změnu šířky');
        await page.locator('#ideas-back').click();
        assert.equal(await page.evaluate(() => window.Vz2Player.getState().collapsed), false);
        assert.equal(await page.evaluate(() => window.Vz2Player.getState().playing), true);
        await page.locator('#player-play').click();
        await page.locator('#show-ideas').click(); assert.equal(await draft.inputValue(), 'Koncept přežije návrat i změnu šířky');
        assert.deepEqual(await prefs(), before);
        check(true, 'ideas: full workspace preserves draft and panel preferences; playing Looper collapses and restores without interruption');
        for (const width of [360, 390, 767, 768, 1024, 1199, 1200, 1280, 1440, 1920]) {
            await page.setViewportSize({ width, height: 800 });
            const geometry = await ideas.evaluate(n => ({ x: n.getBoundingClientRect().x, width: n.clientWidth, workspace: n.parentElement.clientWidth, pageWidth: document.documentElement.scrollWidth, pageHeight: document.documentElement.scrollHeight, scroll: n.querySelector('.panel-body').scrollHeight > n.querySelector('.panel-body').clientHeight }));
            assert.equal(geometry.width, geometry.workspace); assert(geometry.pageWidth <= width + 1); assert(geometry.pageHeight <= 801); assert(geometry.scroll);
            assert.equal(await page.locator('#content-area').isVisible(), false);
        }
        await page.setViewportSize({ width: 1440, height: 900 });
        await page.screenshot({ path: path.join(temp, 'ui-stage4-ideas-desktop.png') });
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: path.join(temp, 'ui-stage4-ideas-mobile.png') });
        await page.setViewportSize({ width: 390, height: 320 }); await draft.focus();
        await ideas.getByRole('button', { name: 'Odeslat', exact: true }).click();
        await ideas.locator('article').getByText('Koncept přežije návrat i změnu šířky', { exact: true }).waitFor();
        await page.locator('[data-mobile-panel=tablature]').click();
        assert.equal(await ideas.isVisible(), false); assert(await page.locator('#panel-tablature').isVisible());
        await page.locator('#bn-napady').click(); assert(await ideas.isVisible());
        assert.equal(await page.locator('[data-mobile-panel][aria-pressed=true]').count(), 0);
        await page.locator('#ideas-back').click(); assert(await page.locator('#panel-tablature').isVisible());
        check(true, 'ideas: all 10 widths fit, independent scroll, mobile navigation and short-height editing preserve workspace state');
        await page.setViewportSize({ width: 1024, height: 800 });
        await page.getByLabel('Levý panel', { exact: true }).selectOption('discussion');
        await page.getByLabel('Pravý panel', { exact: true }).selectOption('tablature');
        await page.locator('#show-ideas').click(); await page.locator('#ideas-back').click();
        assert(await page.locator('#panel-discussion').isVisible()); assert(await page.locator('#panel-tablature').isVisible());
        await page.setViewportSize({ width: 1440, height: 900 });
        await page.locator('#show-ideas').click(); await page.locator('[data-desktop-panel=lyrics]').click();
        assert(await page.locator('#panel-lyrics').isVisible()); assert.equal(await ideas.isVisible(), false);
        const menu = page.locator('#collection-actions details'); await menu.locator('summary').click();
        await page.keyboard.press('Escape'); assert.equal(await menu.getAttribute('open'), null);
        assert.equal(await page.evaluate(() => document.activeElement.tagName), 'SUMMARY');
        await menu.locator('summary').click(); await page.locator('#collection-title').click(); assert.equal(await menu.getAttribute('open'), null);
        assert.deepEqual(errors, []);
        check(true, 'ideas: tablet pair and desktop panels restore; menus close with Escape/outside click; no JavaScript errors');
        await page.locator('#show-ideas').click();
        const own = ideas.locator('article').filter({ hasText: 'Koncept přežije návrat i změnu šířky' });
        await own.getByRole('button', { name: 'Upravit', exact: true }).click(); await draft.fill('Můj upravený nápad');
        const stored = (await request(clients.admin, endpoint + '?action=discussion&scope=ideas')).json().posts.find(p => p.body === 'Koncept přežije návrat i změnu šířky');
        assert.equal((await request(clients.admin, endpoint, { action: 'post_update', thread_id: thread.id, post_id: stored.id, revision: stored.revision, body: 'Souběžná změna nápadu' })).status, 200);
        await ideas.getByRole('button', { name: 'Uložit úpravu', exact: true }).click();
        await ideas.getByRole('button', { name: 'Načíst aktuální příspěvek', exact: true }).click();
        await ideas.locator('pre').filter({ hasText: 'Souběžná změna nápadu' }).waitFor();
        assert.equal(await draft.inputValue(), 'Můj upravený nápad');
        await page.locator('#ideas-back').click(); await page.locator('#show-ideas').click();
        await ideas.getByRole('button', { name: 'Použít aktuální revizi pro můj text', exact: true }).click();
        await ideas.getByRole('button', { name: 'Uložit úpravu', exact: true }).click();
        await ideas.locator('article').getByText('Můj upravený nápad', { exact: true }).waitFor();
        await ideas.locator('article').filter({ hasText: 'Můj upravený nápad' }).getByRole('button', { name: 'Smazat', exact: true }).click();
        await ideas.locator('article').getByText('Můj upravený nápad', { exact: true }).waitFor({ state: 'detached' });
        assert.deepEqual(errors, []);
        check(true, 'ideas: editing conflict survives workspace navigation, explicit revision acceptance saves, deletion updates list');
    } finally { await browser.close(); }
};
