'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');

module.exports = async function ({ base, clients, good, upload, wav, request, db, media, check, temp }) {
    const c = await good('admin', { action: 'collection_create', kind: 'song', title: 'Browser stage 3' });
    const audio = await upload('admin', c.id, 'Běžná nahrávka — zápisy', 'single', ['audio.wav'], [wav(10)]);
    const mix = await upload('admin', c.id, 'Mixér — zápisy', 'multitrack', ['left.wav', 'right.wav'], [wav(10), wav(10)]);
    assert.equal(audio.status, 201, audio.text); assert.equal(mix.status, 201, mix.text);
    const id = audio.json().id, mixId = mix.json().id;
    const endpoint = 'php/ajax/vz2_timestamps.php';
    const post = (rid, fields) => request(clients.admin, endpoint, { recording_id: rid, ...fields });
    const executablePath = [process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH, chromium.executablePath(), 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(p => p && fs.existsSync(p));
    const browser = await chromium.launch({ headless: true, executablePath, args: ['--autoplay-policy=no-user-gesture-required'] });
    try {
        const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
        const [cookieName, cookieValue] = clients.admin.cookie.split('=');
        await context.addCookies([{ name: cookieName, value: cookieValue, url: base }]);
        const page = await context.newPage(), errors = [];
        page.on('pageerror', e => errors.push(e.message));
        page.on('dialog', d => d.accept());
        await page.route('https://cdn.jsdelivr.net/**', route => route.abort());
        await page.goto(base + 'index.php?v=2&view=mixer&collection_id=' + c.id);
        await page.locator('#recording-' + id).waitFor({ state: 'attached' });
        await page.locator('#mt-selector [data-mt-id="' + mixId + '"]').waitFor();
        const mixerBox = await page.locator('#mixer-panel').boundingBox();
        assert(mixerBox && mixerBox.y >= 0 && mixerBox.y < 400, 'Mixer navigation must keep the panel in view after catalogue loading: ' + JSON.stringify(mixerBox));
        assert.equal(await page.locator('.layout').isVisible(), false, 'Mixer view must not show the catalogue above it');
        await page.locator('#mt-selector [data-mt-id="' + mixId + '"]').click();
        await page.waitForFunction(rid => window.MultitrackApp?.getState()?.id === String(rid) && window.MultitrackApp.getState().phase === 'ready', mixId);
        check(true, 'browser: direct Mixer navigation stays visible after asynchronous catalogue load and can open a recording');
        await page.goto(base + 'index.php?v=2&collection_id=' + c.id);
        assert.equal(await page.locator('.layout').isVisible(), true, 'Catalogue navigation restores songs and rehearsals');
        const card = page.locator('#recording-' + id), notes = card.locator('.vz2-timestamps'), dialog = page.locator('.vz2-timestamp-editor');
        await notes.getByRole('button', { name: 'Přidat zápis', exact: true }).click();
        await dialog.locator('[name=kind]').selectOption('song_start');
        await dialog.locator('[name=time]').fill('00:00:01.123');
        await dialog.locator('[name=body]').fill('<img src=x onerror=alert(1)> Začátek');
        await dialog.getByRole('button', { name: 'Uložit', exact: true }).click();
        await dialog.waitFor({ state: 'hidden' });
        await notes.getByText('<img src=x onerror=alert(1)> Začátek', { exact: true }).waitFor();
        assert.equal(await notes.locator('img').count(), 0);
        await notes.getByRole('button', { name: 'Upravit', exact: true }).click();
        await dialog.locator('[name=body]').fill('Můj rozepsaný text');
        const latest = (await request(clients.admin, endpoint + '?recording_id=' + id)).json();
        const existing = latest.entries[0];
        assert.equal((await post(id, { action: 'update', id: existing.id, revision: existing.revision, timestamps_revision: latest.timestamps_revision, kind: existing.kind, time_ms: existing.time_ms, body: 'Úprava z druhého okna' })).status, 200);
        await dialog.getByRole('button', { name: 'Uložit', exact: true }).click();
        await dialog.locator('.ts-rebase').waitFor({ state: 'visible' });
        assert.equal(await dialog.locator('[name=body]').inputValue(), 'Můj rozepsaný text');
        await dialog.locator('.ts-rebase').click();
        await dialog.locator('.ts-current').getByText(/Úprava z druhého okna/).waitFor();
        await dialog.getByRole('button', { name: 'Uložit', exact: true }).click();
        await dialog.waitFor({ state: 'hidden' });
        await notes.getByText('Můj rozepsaný text', { exact: true }).waitFor();
        check(true, 'browser: safe text rendering and 409 preserve draft; explicit comparison/rebase saves it');
        await notes.getByRole('button', { name: 'Přidat zápis', exact: true }).click();
        await dialog.locator('[name=kind]').selectOption('song_start');
        await dialog.locator('[name=time]').fill('00:00:02.000');
        await dialog.locator('[name=body]').fill('Konec úseku');
        await dialog.getByRole('button', { name: 'Uložit a vrátit na čas', exact: true }).click();
        await dialog.waitFor({ state: 'hidden' });
        assert(Math.abs(await card.locator('audio').evaluate(a => a.currentTime) - 2) < 0.05);
        await notes.getByRole('button', { name: 'Smyčka', exact: true }).first().click();
        await notes.getByRole('button', { name: 'Vypnout smyčku', exact: true }).waitFor();
        await page.waitForTimeout(1400);
        const position = await card.locator('audio').evaluate(a => a.currentTime);
        assert(position >= 1.1 && position < 2.15, 'native loop should return within interval: ' + position);
        await notes.getByRole('button', { name: 'Vypnout smyčku', exact: true }).click();
        await card.locator('audio').evaluate(a => a.pause());
        await notes.getByRole('button', { name: 'Kopírovat tabulku', exact: true }).click();
        await notes.getByText('Tabulka zkopírována.', { exact: true }).waitFor();
        assert((await page.evaluate(() => navigator.clipboard.readText())).includes('00:00:01.123\tMůj rozepsaný text'));
        check(true, 'browser: rewind, native audio loop and filtered clipboard table work');
        await notes.getByRole('button', { name: 'Přidat zápis', exact: true }).click();
        await dialog.locator('[name=kind]').selectOption('note'); await dialog.locator('[name=time]').fill('00:00:01.500');
        await dialog.locator('[name=body]').fill('Text přežije obnovení katalogu');
        await page.evaluate(() => window.dispatchEvent(new Event('online')));
        await notes.getByText('Můj rozepsaný text', { exact: true }).waitFor();
        assert.equal(await dialog.locator('[name=body]').inputValue(), 'Text přežije obnovení katalogu');
        await dialog.locator('[name=keep]').check();
        await dialog.getByRole('button', { name: 'Uložit', exact: true }).click();
        await notes.getByText('Text přežije obnovení katalogu', { exact: true }).waitFor();
        assert.equal(await dialog.isVisible(), true); assert.equal(await dialog.locator('[name=body]').inputValue(), '');
        await dialog.getByRole('button', { name: 'Zrušit', exact: true }).click();
        check(true, 'browser: draft survives catalogue refresh and repeated-add form remains open after save');
        const download = page.waitForEvent('download'); await notes.getByRole('link', { name: 'Export TXT' }).click();
        assert.equal((await download).suggestedFilename(), 'nahravka-' + id + '-zapisy.txt');
        await page.locator('#recording-' + mixId).getByRole('button', { name: 'Otevřít Mixér', exact: true }).click();
        await page.waitForFunction(rid => window.MultitrackApp?.getState()?.id === String(rid) && window.MultitrackApp.getState().phase === 'ready', mixId);
        const mixerNotes = page.locator('#mixer-timestamps');
        await mixerNotes.getByRole('button', { name: 'Přidat zápis', exact: true }).click();
        await dialog.locator('[name=time]').fill('00:00:01.000'); await dialog.locator('[name=kind]').selectOption('passage');
        await dialog.locator('[name=body]').fill('Společná pasáž Mixéru');
        await dialog.locator('[name=keep]').uncheck();
        await dialog.getByRole('button', { name: 'Uložit', exact: true }).click(); await dialog.waitFor({ state: 'hidden' });
        await page.locator('#recording-' + mixId).getByText('Společná pasáž Mixéru', { exact: true }).waitFor();
        await mixerNotes.getByRole('button', { name: 'Smyčka', exact: true }).click();
        await page.waitForFunction(() => window.MultitrackApp.getState()?.playing === true);
        await page.evaluate(() => window.MultitrackApp.seek(9.95)); await page.waitForTimeout(400);
        const mixState = await page.evaluate(() => window.MultitrackApp.getState());
        assert(mixState.playing && mixState.position >= 1 && mixState.position < 2, JSON.stringify(mixState));
        await mixerNotes.getByRole('button', { name: 'Vypnout smyčku', exact: true }).click();
        await page.evaluate(() => window.MultitrackApp.pause());
        check(true, 'browser: Mixer and catalogue share saved timestamps; Mixer adapter loops correctly');
        const firstFile = db('SELECT relative_path FROM vz2_audio_files WHERE recording_id=? ORDER BY id', [mixId])[0].relative_path;
        fs.renameSync(path.join(media, firstFile), path.join(media, firstFile + '.held'));
        try {
            await page.reload();
            await page.locator('#recording-' + mixId).getByRole('button', { name: 'Otevřít Mixér', exact: true }).click();
            await page.waitForFunction(() => window.MultitrackApp?.getState()?.phase === 'ready');
            const partial = await page.evaluate(() => window.MultitrackApp.getState());
            assert.equal(partial.tracks.filter(t => t.status === 'ready').length, 1);
            assert.equal(partial.tracks.filter(t => t.status === 'error').length, 1);
            assert((await page.locator('#mt-notice').textContent()).includes('jen úspěšně načtené stopy'));
            check(true, 'browser: incomplete Mixer explicitly continues with available track and shows warning');
        } finally { fs.renameSync(path.join(media, firstFile + '.held'), path.join(media, firstFile)); }
        const recording = db('SELECT * FROM vz2_recordings WHERE id=?', [id])[0];
        await good('admin', { action: 'remove_audio', id, revision: recording.revision, confirm: recording.title, request_key: require('node:crypto').randomBytes(16).toString('hex') });
        await page.reload(); await notes.getByText('Můj rozepsaný text', { exact: true }).waitFor();
        assert.equal(await card.locator('audio').count(), 0);
        for (const b of await notes.locator('[data-playback]').all()) assert.equal(await b.isDisabled(), true);
        assert.equal(await notes.getByRole('button', { name: 'Upravit', exact: true }).first().isEnabled(), true);
        check(true, 'browser: removed audio leaves readable/editable notes while playback controls are disabled');
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: path.join(temp, 'stage3-mobile.png'), fullPage: true });
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'mobile page must not overflow');
        await page.setViewportSize({ width: 1440, height: 1000 });
        await page.screenshot({ path: path.join(temp, 'stage3-desktop.png'), fullPage: true });
        assert.deepEqual(errors, []);
        check(true, 'browser: desktop/mobile layouts fit and no JavaScript errors occur');
    } finally { await browser.close(); }
    const collection = db('SELECT * FROM vz2_collections WHERE id=?', [c.id])[0];
    await good('admin', { action: 'delete_collection', id: c.id, revision: collection.revision, confirm: collection.title, request_key: require('node:crypto').randomBytes(16).toString('hex') });
};
