'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');

module.exports = async ({ base, clients, good, request, upload, wav, db, check, temp }) => {
    const collection = await good('admin', { action: 'collection_create', kind: 'song', title: 'Kompaktní nahrávky' });
    const target = await good('admin', { action: 'collection_create', kind: 'rehearsal', title: 'Cílová zkouška' });
    const ids = [];
    for (const [title, kind, files] of [['První záběr', 'single', ['one.wav']], ['Druhý záběr', 'single', ['two.wav']], ['Kapela', 'multitrack', ['guitar.wav', 'bass.wav']]]) {
        const result = await upload('admin', collection.id, title, kind, files, files.map(() => wav(10)));
        assert.equal(result.status, 201, result.text); ids.push(result.json().id);
    }
    const executablePath = [process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH, chromium.executablePath(), 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(p => p && fs.existsSync(p));
    const browser = await chromium.launch({ headless: true, executablePath, args: ['--autoplay-policy=no-user-gesture-required'] });
    try {
        const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, permissions: ['clipboard-read', 'clipboard-write'] });
        const [name, value] = clients.admin.cookie.split('='); await context.addCookies([{ name, value, url: base }]);
        const page = await context.newPage(), errors = [];
        page.on('pageerror', e => errors.push(e.message));
        page.on('dialog', d => d.accept());
        await page.route('https://cdn.jsdelivr.net/**', r => r.abort());
        await page.goto(base + 'index.php?v=2&collection_id=' + collection.id);
        const card = id => page.locator('#recording-' + id), expanded = () => page.locator('.recording-toggle[aria-expanded=true]').count();
        await card(ids[2]).waitFor();
        assert.equal(await expanded(), 0);
        await page.screenshot({ path: path.join(temp, 'ui-stage2-desktop-collapsed.png') });
        for (const id of ids) await card(id).locator('.recording-toggle').click();
        assert.equal(await expanded(), 3);
        assert.equal(await page.evaluate(() => window.MultitrackApp.getState()), null);
        const audio = card(ids[0]).locator('audio');
        await audio.evaluate(async a => { if (a.readyState < 1) await new Promise(r => a.addEventListener('loadedmetadata', r, { once: true })); a.currentTime = 2; await a.play(); });
        assert.equal(await audio.evaluate(a => a.paused), false);
        await audio.evaluate(a => a.pause());
        const position = await audio.evaluate(a => a.currentTime);
        await card(ids[0]).locator('.recording-toggle').click();
        assert.equal(await expanded(), 2);
        await card(ids[0]).locator('.recording-toggle').click();
        assert(Math.abs(await audio.evaluate(a => a.currentTime) - position) < 0.1);
        assert.equal(await page.evaluate(() => window.MultitrackApp.getState()), null);
        check(true, 'recordings: initially collapsed, any number open, native playback and position survive collapse without opening Mixer');
        const actions = card(ids[0]).locator('.recording-body > .recording-actions');
        const menu = actions.locator(':scope > .actions-menu > .action-list');
        const menuToggle = actions.locator(':scope > .actions-menu > summary');
        assert.equal(await actions.locator(':scope > .actions-menu').count(), 1, 'Selected recording actions share one disclosure button');
        assert.equal(await card(ids[0]).locator('.recording-body > .files a').count(), 0, 'Download is no longer displayed above the action menu');
        assert.equal(await card(ids[0]).locator(':scope > button:not(.recording-toggle)').count(), 0, 'Open action is not detached at the top of the recording card');
        assert.deepEqual((await actions.locator(':scope > button').allTextContents()).slice(0, 2), ['Uložit offline', 'Otevřít'], 'Offline and open actions remain directly visible');
        await actions.getByRole('button', { name: 'Uložit offline', exact: true }).click();
        await actions.getByRole('button', { name: 'Odebrat offline kopii', exact: true }).waitFor();
        await menuToggle.click();
        await menu.getByRole('button', { name: 'Kopírovat odkaz na čas', exact: true }).click();
        const link = await page.evaluate(() => navigator.clipboard.readText());
        assert.equal(new URL(link).searchParams.get('recording_id'), String(ids[0]));
        await menu.getByRole('button', { name: 'Upravit', exact: true }).click();
        await page.locator('#edit-form [name=title]').fill('Přejmenovaný záběr');
        await page.locator('#edit-form').getByRole('button', { name: 'Uložit', exact: true }).click();
        await card(ids[0]).getByText('Přejmenovaný záběr', { exact: true }).waitFor();
        assert.equal(await expanded(), 3, 'Catalog refresh preserves in-document expansion');
        await page.reload();
        await card(ids[2]).waitFor(); assert.equal(await expanded(), 0);
        await card(ids[0]).locator('.recording-toggle').click();
        await actions.getByRole('button', { name: 'Odebrat offline kopii', exact: true }).waitFor();
        assert((await audio.getAttribute('src')).startsWith('blob:'));
        await actions.getByRole('button', { name: 'Odebrat offline kopii', exact: true }).click();
        await actions.getByRole('button', { name: 'Uložit offline', exact: true }).waitFor();
        check(true, 'recordings: actions menu retains offline cache, time links and rename; refresh preserves expansion but reload clears it');
        await page.goto(link);
        await card(ids[0]).waitFor(); assert.equal(await expanded(), 0);
        await card(ids[0]).locator('.recording-toggle').click();
        await page.waitForFunction(({ id, position }) => Math.abs(document.querySelector('#recording-' + id + ' audio').currentTime - position) < 0.1, { id: ids[0], position });
        assert.equal(await menu.getByLabel('Cílová skladba nebo zkouška').count(), 0, 'Move destination is hidden from the action list until requested');
        await menuToggle.click();
        await menu.getByRole('button', { name: 'Přesunout', exact: true }).click();
        const moveDialog = page.locator('#move-dialog');
        await moveDialog.waitFor({ state: 'visible' });
        await moveDialog.getByLabel('Cílová skladba nebo zkouška').selectOption(String(target.id));
        await moveDialog.getByRole('button', { name: 'Potvrdit přesun', exact: true }).click();
        await page.locator('#collection-title').getByText('Cílová zkouška', { exact: true }).waitFor();
        assert.equal(Number(db('SELECT collection_id FROM vz2_recordings WHERE id=?', [ids[0]])[0].collection_id), target.id);
        check(true, 'recordings: collapsed reload keeps deep-link time; move menu preserves recording identity and follows new parent');
        await page.goto(base + 'index.php?v=2&collection_id=' + collection.id);
        await card(ids[1]).waitFor();
        await card(ids[2]).locator('.recording-toggle').click();
        await card(ids[2]).locator('.recording-body > .recording-actions').getByRole('button', { name: 'Otevřít Mixér', exact: true }).waitFor();
        assert.equal(await card(ids[2]).locator(':scope > button:not(.recording-toggle)').count(), 0, 'Mixer action is not detached at the top of the recording card');
        await page.setViewportSize({ width: 390, height: 844 });
        await page.waitForFunction(() => document.body.dataset.layout === 'mobile');
        await page.screenshot({ path: path.join(temp, 'ui-stage2-mobile-collapsed.png') });
        await card(ids[1]).locator('.recording-toggle').click();
        await page.waitForFunction(id => document.querySelector('#recording-' + id + ' audio').readyState >= 1, ids[1]);
        assert.equal(await card(ids[1]).locator('.recording-actions').count(), 1, 'Single audio retains one shared action list');
        // Chromium animates native media controls after revealing a hidden audio.
        await page.waitForTimeout(500);
        await card(ids[1]).locator('audio').click({ position: { x: 25, y: 27 } });
        await page.waitForFunction(id => !document.querySelector('#recording-' + id + ' audio').paused, ids[1]);
        await card(ids[1]).locator('audio').evaluate(a => a.pause());
        await page.screenshot({ path: path.join(temp, 'ui-stage2-mobile-expanded.png') });
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight));
        const guestContext = await browser.newContext({ viewport: { width: 1280, height: 800 } });
        const [guestName, guestValue] = clients.guest.cookie.split('='); await guestContext.addCookies([{ name: guestName, value: guestValue, url: base }]);
        const guest = await guestContext.newPage(); await guest.route('https://cdn.jsdelivr.net/**', r => r.abort());
        await guest.goto(base + 'index.php?v=2&collection_id=' + collection.id);
        await guest.locator('#recording-' + ids[1] + ' .recording-toggle').click();
        const guestMenu = guest.locator('#recording-' + ids[1] + ' .recording-body > .recording-actions > .actions-menu > .action-list');
        assert.equal(await guestMenu.getByRole('button', { name: 'Upravit', exact: true }).count(), 0);
        assert.equal(await guestMenu.getByRole('button', { name: /smazat|Odstranit audio|Přesunout/ }).count(), 0);
        assert.equal(await guest.locator('.upload-section').count(), 0);
        assert.deepEqual(errors, []);
        check(true, 'recordings: mobile collapsed/expanded views fit; guest menus retain read-only permissions');
    } finally { await browser.close(); }
};
