'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { chromium } = require('playwright');

module.exports = async ({ base, clients, good, upload, wav, request, db, check, temp }) => {
    const song = await good('admin', { action: 'collection_create', kind: 'song', title: 'Navigace — skladba' });
    const rehearsal = await good('admin', { action: 'collection_create', kind: 'rehearsal', title: 'Navigace — zkouška' });
    const single = (await upload('admin', song.id, 'Běžná nahrávka', 'single', ['single.wav'], [wav(5)])).json();
    const mix = (await upload('admin', song.id, 'Vícestopá nahrávka', 'multitrack', ['guitar.wav', 'bass.wav'], [wav(5), wav(5)])).json();
    const originalFiles = db('SELECT id,relative_path,sha256 FROM vz2_audio_files WHERE recording_id=? ORDER BY id', [mix.id]);
    const executablePath = [process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH, chromium.executablePath(),
        'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(p => p && fs.existsSync(p));
    const browser = await chromium.launch({ headless: true, executablePath, args: ['--autoplay-policy=no-user-gesture-required'] });
    try {
        const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'] });
        const [name, value] = clients.admin.cookie.split('='); await context.addCookies([{ name, value, url: base }]);
        const page = await context.newPage(), errors = [];
        page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => d.accept());
        await page.route('https://cdn.jsdelivr.net/**', r => r.abort());
        const open = () => page.locator('#recording-' + mix.id).getByRole('button', { name: 'Otevřít Mixér', exact: true }).click();
        const ready = () => page.waitForFunction(id => window.MultitrackApp?.getState()?.id === String(id) && window.MultitrackApp.getState().phase === 'ready', mix.id);
        await page.goto(base + 'index.php?v=2&collection_id=' + song.id);
        await page.locator('#recording-' + single.id + ' .recording-toggle').click();
        await page.locator('#recording-' + single.id + ' audio').waitFor();
        assert.equal(await page.locator('header a').filter({ hasText: /^Mixér$/ }).count(), 0);
        await page.evaluate(() => { window.navigationSentinel = 'same-document'; });
        await open(); await ready();
        assert.equal(await page.locator('#player-body > #mixer-panel').count(), 1);
        assert.equal(await page.locator('#recording-' + mix.id + ' .vz2-timestamps').count(), 1);
        assert.equal(await page.locator('#mt-selector button').count(), 0);
        assert.equal(await page.locator('#collections').isVisible(), true);
        assert((await page.locator('#mixer-context').textContent()).includes('Navigace — skladba'));
        assert.equal(new URL(page.url()).searchParams.get('recording_id'), String(mix.id));
        assert.equal(await page.locator('#recording-' + single.id).count(), 1);
        check(true, 'navigation: single and multitrack share one catalogue and Mixer opens above its panels');
        await page.evaluate(() => { window.MultitrackApp.seek(2); });
        await page.locator('#player-options > summary').click(); await page.locator('#mixer-copy-link').click();
        const copied = new URL(await page.evaluate(() => navigator.clipboard.readText()));
        assert.equal(copied.searchParams.get('recording_id'), String(mix.id));
        assert.equal(copied.searchParams.get('time_ms'), '2000');
        await page.reload(); await ready();
        assert.equal(await page.locator('#mixer-context').count(), 1);
        await page.goto(copied.href); await ready();
        assert(Math.abs((await page.evaluate(() => window.MultitrackApp.getState())).position - 2) < 0.1);
        check(true, 'navigation: reload and copied direct time link reopen the same Mixer recording');
        await page.evaluate(() => { window.navigationSentinel = 'same-document'; window.MultitrackApp.play(); });
        await page.locator('#player-close').click();
        assert.equal(await page.locator('#mixer-panel').isVisible(), false);
        assert.equal(await page.evaluate(() => window.MultitrackApp.getState()), null);
        await page.goBack(); await ready();
        assert.equal(await page.evaluate(() => window.navigationSentinel), 'same-document');
        assert(Math.abs((await page.evaluate(() => window.MultitrackApp.getState())).position - 2) < 0.1);
        await page.goForward();
        await page.waitForFunction(() => window.MultitrackApp.getState() === null);
        check(true, 'navigation: close stops playback; browser Back/Forward restores route without reloading page');
        await open(); await ready();
        await page.locator('[data-kind=rehearsal]').click();
        await page.getByRole('heading', { name: 'Navigace — zkouška', exact: true }).waitFor();
        assert.equal(await page.locator('#mixer-panel').isVisible(), false);
        assert.equal(await page.evaluate(() => window.MultitrackApp.getState()), null);
        await page.reload();
        await page.getByRole('heading', { name: 'Navigace — zkouška', exact: true }).waitFor();
        await page.getByText('Tento celek zatím nemá žádné nahrávky.', { exact: true }).waitFor();
        check(true, 'navigation: switching to an empty rehearsal stops Mixer and retains rehearsal on reload');
        // A late list response may not load hidden audio after the user leaves.
        await page.goto(base + 'index.php?v=2&collection_id=' + song.id);
        let release; const held = new Promise(resolve => { release = resolve; });
        let reached; const waiting = new Promise(resolve => { reached = resolve; });
        const matcher = url => url.pathname.endsWith('/php/ajax/vz2.php') && url.searchParams.get('action') === 'mixer' && !url.searchParams.has('id');
        await page.route(matcher, async route => { reached(); await held; await route.continue(); });
        await open(); await waiting;
        await page.locator('[data-kind=rehearsal]').click();
        const response = page.waitForResponse(r => matcher(new URL(r.url())));
        release(); await (await response).finished();
        await page.waitForTimeout(150);
        assert.equal(await page.evaluate(() => window.MultitrackApp.getState()), null);
        assert.equal(await page.locator('#mixer-panel').isVisible(), false);
        await page.unroute(matcher);
        check(true, 'navigation: stale Mixer list cannot reopen playback after collection switch');
        const current = db('SELECT revision FROM vz2_recordings WHERE id=?', [mix.id])[0];
        await good('admin', { action: 'recording_move', id: mix.id, revision: current.revision, collection_id: rehearsal.id });
        await page.goto(base + 'index.php?v=2&collection_id=' + song.id + '&recording_id=' + mix.id + '&view=mixer&time_ms=1000');
        await ready();
        assert.equal(new URL(page.url()).searchParams.get('collection_id'), String(rehearsal.id));
        assert((await page.locator('#mixer-context').textContent()).includes('Navigace — zkouška'));
        assert.equal(await page.locator('[data-kind=rehearsal]').getAttribute('aria-pressed'), 'true');
        assert.deepEqual(db('SELECT id,relative_path,sha256 FROM vz2_audio_files WHERE recording_id=? ORDER BY id', [mix.id]), originalFiles);
        check(true, 'navigation: old link follows moved recording to current parent without changing file identities');
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: path.join(temp, 'stage6-mobile.png'), fullPage: true });
        assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
        await page.setViewportSize({ width: 1440, height: 1000 });
        await page.screenshot({ path: path.join(temp, 'stage6-desktop.png'), fullPage: true });
        const guestContext = await browser.newContext();
        const [guestName, guestValue] = clients.guest.cookie.split('='); await guestContext.addCookies([{ name: guestName, value: guestValue, url: base }]);
        const guest = await guestContext.newPage(); await guest.route('https://cdn.jsdelivr.net/**', r => r.abort());
        await guest.goto(base + 'index.php?v=2&recording_id=' + mix.id);
        await guest.waitForFunction(() => window.MultitrackApp?.getState()?.phase === 'ready');
        assert.equal(await guest.locator('#create-collection').count(), 0);
        assert.equal(await guest.locator('#mixer-timestamps').getByRole('button', { name: 'Přidat zápis', exact: true }).count(), 0);
        check(true, 'navigation: guest may open shared Mixer; mobile layout fits without introducing write controls');
        const row = db('SELECT title,revision FROM vz2_recordings WHERE id=?', [mix.id])[0];
        await good('admin', { action: 'remove_audio', id: mix.id, revision: row.revision, confirm: row.title, request_key: crypto.randomBytes(16).toString('hex') });
        await page.reload();
        await page.waitForFunction(() => window.MultitrackApp?.getState()?.phase === 'archived');
        assert.equal(await page.locator('#mixer-timestamps').isVisible(), true);
        assert.equal(await page.locator('#mt-play').isDisabled(), true);
        check(true, 'navigation: direct Mixer link keeps notes available after removing audio');
        const removed = db('SELECT title,revision FROM vz2_recordings WHERE id=?', [mix.id])[0];
        await good('admin', { action: 'delete_recording', id: mix.id, revision: removed.revision, confirm: removed.title, request_key: crypto.randomBytes(16).toString('hex') });
        await page.reload(); await page.getByText('Odkazovaná nahrávka již neexistuje.', { exact: true }).waitFor();
        assert.equal(await page.locator('#mixer-panel').isVisible(), false);
        assert.equal(await page.evaluate(() => window.MultitrackApp.getState()), null);
        assert.deepEqual(errors, []);
        check(true, 'navigation: deleted recording link shows clear result and never loads another recording; no JS errors');
    } finally { await browser.close(); }
    for (const id of [song.id, rehearsal.id]) {
        const row = db('SELECT title,revision FROM vz2_collections WHERE id=?', [id])[0];
        await good('admin', { action: 'delete_collection', id, revision: row.revision, confirm: row.title, request_key: crypto.randomBytes(16).toString('hex') });
    }
};
