'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
module.exports = async ({ base, clients, good, request, db, check, temp }) => {
    const song = await good('admin', { action: 'collection_create', kind: 'song', title: 'Mapa — browser' });
    const other = await good('admin', { action: 'collection_create', kind: 'song', title: 'Mapa — jiná skladba' });
    const endpoint = 'php/ajax/vz2_content.php';
    const getMap = () => request(clients.admin, endpoint + '?' + new URLSearchParams({ action: 'document', collection_id: song.id, kind: 'song_map' }));
    // Old text and history must survive replacing their UI slot.
    assert.equal((await request(clients.admin, endpoint, { action: 'document_save', collection_id: song.id, kind: 'tablature', document_id: null, current_revision: 0, title: 'Původní tabulatura', body: 'e|---0---|' })).status, 200);
    const executablePath = [process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH, chromium.executablePath(), 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(p => p && fs.existsSync(p));
    const browser = await chromium.launch({ headless: true, executablePath }); const errors = [];
    async function pageFor(client = 'admin') {
        const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
        const [name, value] = clients[client].cookie.split('='); await context.addCookies([{ name, value, url: base }]);
        const page = await context.newPage(); page.on('pageerror', e => errors.push(e.message));
        await page.route('https://cdn.jsdelivr.net/**', r => r.abort());
        await page.goto(base + 'index.php?v=2&collection_id=' + song.id);
        await page.waitForFunction(() => document.querySelector('#tablature-content .song-map') || document.getElementById('tablature-content').textContent.includes('Tato skladba zatím nemá mapu.'));
        return page;
    }
    const mapHost = page => page.locator('#tablature-content');
    const mode = (page, name) => mapHost(page).getByRole('button', { name, exact: true }).click();
    const type = (page, name) => mapHost(page).locator('[data-type=' + JSON.stringify(name) + ']').click();
    const bars = page => mapHost(page).locator('.song-map-bar');
    const dialog = (page, name) => page.getByRole('dialog', { name, exact: true });
    const save = async (page, revision) => {
        await page.locator('#tablature-actions').getByRole('button', { name: 'Uložit mapu', exact: true }).click();
        await mapHost(page).getByText('Mapa uložena · verze ' + revision, { exact: true }).waitFor();
    };
    try {
        const page = await pageFor(), host = mapHost(page);
        assert.equal(await page.locator('[data-desktop-panel]').count(), 4);
        assert.equal(await page.locator('[data-mobile-panel]').count(), 4);
        assert.equal((await getMap()).json().document, null);
        await host.getByRole('button', { name: 'Vytvořit mapu', exact: true }).click();
        const first = dialog(page, 'Nová sekce'); await first.waitFor();
        assert.equal(await first.locator('select').inputValue(), ''); assert.equal(await bars(page).count(), 0);
        await first.locator('input').fill('Sloka'); await first.getByRole('button', { name: 'Použít sekci', exact: true }).click();
        assert.equal(await host.locator('.song-map-section').count(), 0);
        await mode(page, 'ZÁPIS POSLECHEM');
        await type(page, 'HH+CRASH'); for (let i = 0; i < 7; i++) await type(page, 'HI-HAT');
        assert.equal(await bars(page).count(), 8); assert.equal(await host.locator('.song-map-section').count(), 1);
        await host.getByRole('button', { name: 'Refrén', exact: true }).click(); await host.getByRole('button', { name: 'Bridge', exact: true }).click();
        assert.equal(await host.locator('.song-map-section').count(), 1); assert.equal(await bars(page).count(), 8);
        await type(page, 'RD+F3'); assert.equal(await host.locator('.song-map-section').count(), 2);
        await host.getByRole('button', { name: '↶ Zpět', exact: true }).click(); assert.equal(await host.locator('.song-map-section').count(), 1);
        await host.getByRole('button', { name: 'Refrén', exact: true }).click(); await type(page, 'F4');
        await type(page, '?'); await type(page, 'Pauza'); await type(page, 'Stop');
        assert.equal(await bars(page).count(), 12);
        assert.equal((await getMap()).json().document, null, 'no autosave during listening');
        check(true, 'map browser: four panels, explicit first section, one-click palette, pending boundary replacement, special bars and Undo of first new-section bar');
        await mode(page, 'UPRAVIT');
        const originalId = await bars(page).first().getAttribute('data-bar-id');
        await bars(page).first().click(); await host.getByRole('button', { name: 'Vložit před', exact: true }).click();
        assert.equal(await bars(page).count(), 13); assert((await bars(page).first().getAttribute('aria-label')).includes('Neurčený'));
        assert.equal(await bars(page).nth(1).getAttribute('data-bar-id'), originalId);
        assert.equal(await bars(page).first().getAttribute('aria-pressed'), 'true');
        await host.getByRole('button', { name: '↶ Zpět', exact: true }).click();
        await bars(page).nth(7).click(); await host.getByRole('button', { name: 'Vložit za', exact: true }).click();
        assert.equal(await host.locator('.song-map-section').first().locator('.song-map-bar').count(), 9);
        assert.equal(await host.locator('.song-map-section').nth(1).locator('.song-map-bar').count(), 4);
        await host.getByRole('button', { name: 'Odstranit takt', exact: true }).click();
        await host.getByRole('button', { name: '↶ Zpět', exact: true }).click(); assert.equal(await bars(page).count(), 13);
        await host.getByRole('button', { name: '↶ Zpět', exact: true }).click(); assert.equal(await bars(page).count(), 12);
        await bars(page).first().click(); await type(page, 'RIDE'); assert((await bars(page).first().getAttribute('aria-label')).includes('Ride'));
        await host.getByRole('button', { name: 'Vybrat takt', exact: true }).click();
        await host.getByRole('button', { name: 'Posunout takt →', exact: true }).click();
        assert.equal(await bars(page).nth(1).getAttribute('data-bar-id'), originalId);
        await host.getByRole('button', { name: '↶ Zpět', exact: true }).click();
        const detailText = '  HH | x-x-x-x-\nSN | --o---o-\n<img src=x onerror=alert(1)>\n';
        await host.getByRole('button', { name: 'Detail taktu', exact: true }).click();
        await dialog(page, 'Detail taktu').locator('textarea').fill(detailText);
        await dialog(page, 'Detail taktu').getByRole('button', { name: 'Uložit detail', exact: true }).click();
        assert.equal((await getMap()).json().document, null);
        await host.getByRole('button', { name: 'Kopírovat detail', exact: true }).click(); await bars(page).nth(1).click(); await bars(page).nth(2).click();
        await host.getByRole('button', { name: 'Použít detail na vybrané takty', exact: true }).click();
        await bars(page).first().click(); await host.getByRole('button', { name: 'Detail taktu', exact: true }).click();
        await dialog(page, 'Detail taktu').locator('textarea').fill('source changed');
        await dialog(page, 'Detail taktu').getByRole('button', { name: 'Uložit detail', exact: true }).click();
        await bars(page).nth(1).click(); await host.getByRole('button', { name: 'Detail taktu', exact: true }).click();
        assert.equal(await dialog(page, 'Detail taktu').locator('textarea').inputValue(), detailText);
        await dialog(page, 'Detail taktu').getByRole('button', { name: 'Zrušit', exact: true }).click();
        await host.getByRole('button', { name: 'Kopírovat detail', exact: true }).click(); await bars(page).nth(2).click();
        await host.getByRole('button', { name: 'Použít detail na vybrané takty', exact: true }).click();
        await dialog(page, 'Přepsat Detaily').getByRole('button', { name: 'Zrušit', exact: true }).click();
        await host.getByRole('button', { name: 'Ukončit kopírování', exact: true }).click();
        const chorus = host.locator('.song-map-section').nth(1); await chorus.getByRole('button', { name: 'Duplikovat', exact: true }).click();
        assert.equal(await host.locator('.song-map-section').count(), 3);
        assert.equal(await host.locator('.song-map-section h3').nth(2).textContent(), 'Refrén 2');
        await host.locator('.song-map-section').nth(2).getByRole('button', { name: 'Smazat sekci', exact: true }).click();
        assert.equal(await host.locator('.song-map-section').count(), 3);
        await dialog(page, 'Smazat sekci').getByRole('button', { name: 'Smazat sekci', exact: true }).click();
        assert.equal(await host.locator('.song-map-section').count(), 2);
        await host.getByRole('button', { name: '↶ Zpět', exact: true }).click();
        await save(page, 1);
        const saved = (await getMap()).json(); assert.equal(saved.document.current_revision, 1);
        assert.equal(db("SELECT COUNT(*) n FROM vz2_documents WHERE collection_id=? AND kind='tablature'", [song.id])[0].n, 1);
        const ids = JSON.parse(saved.version.body).sections.flatMap(s => [s.id, ...s.bars.map(b => b.id)]); assert.equal(new Set(ids).size, ids.length);
        check(true, 'map browser: insert boundaries/stable IDs, delete and Undo, semantic edit, reorder, exact text details, independent batch copy, overwrite confirmation, duplicate and delete section');
        await bars(page).first().click(); await type(page, 'HH+F1');
        const refreshed = page.waitForResponse(r => new URL(r.url()).pathname.endsWith('/php/ajax/vz2.php') && new URL(r.url()).searchParams.get('action') === 'catalog');
        await page.evaluate(() => window.dispatchEvent(new Event('online'))); await (await refreshed).finished();
        assert((await bars(page).first().getAttribute('aria-label')).includes('F1'), 'draft survives catalog refresh');
        assert.equal(await page.locator('#tablature-actions .song-map-save-state').textContent(), 'Neuloženo');
        await save(page, 2);
        await page.locator('#tablature-actions').getByRole('button', { name: 'Historie mapy', exact: true }).click();
        const history = dialog(page, 'Historie mapy'); await history.locator('.song-map-history-row').first().waitFor();
        assert.equal(await history.locator('.song-map-history-row').count(), 2);
        await history.locator('.song-map-history-row').nth(1).getByRole('button', { name: 'Zobrazit', exact: true }).click();
        const version = dialog(page, 'Verze 1'); await version.waitFor(); assert.equal(await version.locator('.song-map-row').first().locator('.song-map-bar').count(), 8);
        await version.locator('.song-map-bar').first().click();
        assert(await dialog(page, 'Detail taktu').locator('textarea').getAttribute('readonly') !== null);
        await dialog(page, 'Detail taktu').getByRole('button', { name: 'Zavřít', exact: true }).click();
        await version.getByRole('button', { name: 'Obnovit tuto verzi', exact: true }).click();
        await dialog(page, 'Obnovit Mapu').getByRole('button', { name: 'Obnovit tuto verzi', exact: true }).click();
        await host.getByText('Mapa uložena · verze 3', { exact: true }).waitFor(); assert.equal((await getMap()).json().version.body, saved.version.body);
        const racer = await pageFor(); await mode(racer, 'UPRAVIT'); await bars(racer).first().click(); await type(racer, 'HH+F2');
        await bars(page).first().click(); await type(page, 'HH+F3'); await save(page, 4);
        await racer.locator('#tablature-actions').getByRole('button', { name: 'Uložit mapu', exact: true }).click();
        await mapHost(racer).getByRole('button', { name: 'Porovnat aktuální verzi', exact: true }).waitFor();
        assert((await bars(racer).first().getAttribute('aria-label')).includes('F2'));
        await racer.close(); check(true, 'map browser: explicit snapshot versions, history preview/restore and two-editor conflict retains unsaved work');
        await mode(page, 'MAPA'); assert.equal(await host.locator('.song-map-palette').count(), 0); assert.equal(await host.locator('.song-map-number').count(), 0);
        for (const width of [1440, 1024, 768, 390, 320]) {
            await page.setViewportSize({ width, height: 900 });
            if (width < 768) await page.locator('[data-mobile-panel=tablature]').click();
            if (width >= 768 && width < 1200) await page.getByLabel('Levý panel', { exact: true }).selectOption('tablature');
            const row = await host.locator('.song-map-row').first().evaluate(n => {
                const cells = [...n.children].map(b => b.getBoundingClientRect());
                return { count: cells.length, positions: cells.map(b => b.top), overflow: n.scrollWidth > n.clientWidth + 1, groupGap: cells[4].left - cells[3].right, cellGap: cells[1].left - cells[0].right };
            });
            assert.equal(row.count, 8); assert.equal(new Set(row.positions).size, 1); assert(!row.overflow);
            assert(row.groupGap > row.cellGap, '4 + 4 grouping remains visible');
            assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
            await page.screenshot({ path: path.join(temp, 'song-map-' + width + '.png') });
        }
        await bars(page).first().click();
        const mapDetail = dialog(page, 'Detail taktu');
        await mapDetail.locator('textarea').fill('Detail upravený přímo v MAPĚ');
        await mapDetail.getByRole('button', { name: 'Uložit detail', exact: true }).click();
        assert.equal(await page.locator('#tablature-actions .song-map-save-state').textContent(), 'Neuloženo');
        assert.equal(await host.locator('.song-map-palette').count(), 0);
        await save(page, 5);
        assert.equal(JSON.parse((await getMap()).json().version.body).sections[0].bars[0].detail, 'Detail upravený přímo v MAPĚ');
        await mode(page, 'UPRAVIT'); await bars(page).first().click(); await type(page, 'HI-HAT');
        await page.locator('[data-mobile-panel=lyrics]').click();
        await dialog(page, 'Neuložené změny').getByRole('button', { name: 'Zůstat', exact: true }).click();
        assert.equal(await page.locator('#panel-tablature').isVisible(), true);
        await page.locator('[data-mobile-panel=lyrics]').click();
        await dialog(page, 'Neuložené změny').getByRole('button', { name: 'Zahodit změny', exact: true }).click();
        assert.equal(await page.locator('#panel-lyrics').isVisible(), true);
        await page.setViewportSize({ width: 1440, height: 900 });
        await mode(page, 'UPRAVIT'); await bars(page).first().click(); await type(page, 'HI-HAT');
        await page.locator('#catalog-picker').click(); await page.locator('#collections > .collection').filter({ hasText: other.title || 'Mapa — jiná skladba' }).locator('button').first().click();
        await dialog(page, 'Neuložené změny').getByRole('button', { name: 'Zůstat', exact: true }).click();
        assert.equal(new URL(page.url()).searchParams.get('collection_id'), String(song.id));
        if (await page.locator('#catalog-close').isVisible()) await page.locator('#catalog-close').click();
        const guest = await pageFor('guest'); assert.equal(await mapHost(guest).getByRole('button', { name: 'UPRAVIT', exact: true }).count(), 0);
        assert.equal(await guest.locator('#tablature-actions').getByRole('button', { name: 'Uložit mapu', exact: true }).count(), 0);
        await bars(guest).first().click(); assert(await dialog(guest, 'Detail taktu').locator('textarea').getAttribute('readonly') !== null);
        check(true, 'map browser: compact MAPA at five viewport widths, fixed 8/4+4, no horizontal overflow, dirty panel/navigation guard and guest read-only Detail');
        assert.deepEqual(errors, []);
    } finally { await browser.close(); }
};
