'use strict';
const assert = require('node:assert/strict');
const { Draft, types } = require('../../js/vz2-song-map-model');
const hh = types.find(t => t.name === 'HI-HAT'), ride = types.find(t => t.name === 'RIDE');
const draft = new Draft();
draft.create(); assert(draft.dirty); assert.equal(draft.sections.length, 0);
const noSection = new Draft(); noSection.create(); assert(noSection.append(hh));
assert.equal(noSection.sections[0].name, 'Bez sekce'); noSection.undo(); assert.equal(noSection.sections.length, 0);
draft.queue('Sloka'); draft.queue('Refrén'); assert.equal(draft.sections.length, 0);
draft.append(hh); assert.equal(draft.sections[0].name, 'Refrén 1');
const firstSection = draft.sections[0].id, firstBar = draft.selected;
draft.append(ride); const secondBar = draft.selected;
draft.queue('Bridge'); draft.append(hh); assert.equal(draft.sections.length, 2);
draft.undo(); assert.equal(draft.sections.length, 1); assert.equal(draft.selected, secondBar); assert.equal(draft.pending, null);
draft.selected = firstBar; draft.insert(false); const inserted = draft.selected;
assert.equal(draft.find().index, 0); assert.equal(draft.find().section.id, firstSection); assert.equal(draft.find().bar.special, 'unknown');
assert.equal(draft.find(firstBar).index, 1); draft.undo(); assert.equal(draft.find(firstBar).index, 0);
draft.selected = secondBar; draft.insert(true); assert.equal(draft.find().index, 2); assert.equal(draft.find().section.id, firstSection);
draft.removeBar(); draft.undo(); assert.equal(draft.find().index, 2); draft.undo(); assert.equal(draft.find(inserted), null);
draft.selected = firstBar; draft.setDetail(firstBar, 'HH | x-x-x-x-\ntext'); draft.copyDetail(firstBar, [secondBar]);
draft.setDetail(firstBar, 'edited source'); assert.equal(draft.find(secondBar).bar.detail, 'HH | x-x-x-x-\ntext');
draft.duplicate(firstSection); assert.equal(draft.sections[1].name, 'Refrén 2');
assert.notEqual(draft.sections[1].id, firstSection); assert.notEqual(draft.sections[1].bars[0].id, firstBar);
draft.setDetail(draft.sections[1].bars[0].id, 'copy changed'); assert.equal(draft.find(firstBar).bar.detail, 'edited source');
draft.setType(ride); assert.equal(draft.find(firstBar).bar.base, 'ride'); draft.undo(); assert.equal(draft.find(firstBar).bar.base, 'hihat');
draft.moveBar(1); assert.equal(draft.find(firstBar).index, 1); draft.undo(); assert.equal(draft.find(firstBar).index, 0);
const secondSection = draft.sections[1].id; draft.moveSection(secondSection, -1); assert.equal(draft.sections[0].id, secondSection); draft.undo();
draft.removeSection(secondSection); assert.equal(draft.sections.length, 1); draft.undo(); assert.equal(draft.sections.length, 2);
const snapshot = JSON.stringify(draft.map); draft.reset(draft.map); assert(!draft.dirty); assert.equal(JSON.stringify(draft.map), snapshot);
const single = new Draft(); single.create(); single.queue('Outro'); single.append(hh); single.removeBar(); assert.equal(single.sections.length, 0); single.undo(); assert.equal(single.sections.length, 1);
assert.equal(new Set(types.map(t => t.name)).size, 14);
console.log('PASS map model: optional first section, pending section, insert boundaries, delete/Undo, stable IDs, independent copies, semantic edits, reorder and clean state');
